# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/

# Appearance
appearance:
  mode: system  # or "light" / "dark"
  color: emerald  # You can change to other Tailwind colors like "slate", "sky", etc.

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'InnovatorAI-Hub'
    description: 'Portfolio of an AI/ML and MLOps Engineer. Showcasing projects, publications, and professional experience.'
    twitter: 'https://x.com/MUHAMMADYO67186'  # Change or leave blank
  analytics:
    google_analytics: '11414046298'  # Add your GA ID if needed
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "MUHAMMAD YOUSAF RANA"  # Put your real name or brand here

# Site footer
footer:
  copyright:
    notice: '© {year} MUHAMMAD YOUSAF RANA. All rights reserved.'
    license:
      enable: false  # Turned off unless you want to show Creative Commons license

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false  # Enable later if you need LaTeX or math notation
  privacy_pack:
    enable: false  # Enable if GDPR tools are needed
